### ISSUE TITLE
Bedrock Model Viewing

### ISSUE THREAD

**Issue by BobtheBob123456** [Ticxo/Model-Engine-Wiki#19]
Hi Model Engine Team,
I am contacting you because I run a geyser server and wondering if there is a way for bedrock players to view the custom models? If so, how would I do it?

Thanks,
Ishaan

**Comment by JohnnyX071** [comment]
Yea, I believe geyser added support for that yesterday but its up to the model engine developers to add support for it

**Comment by BobtheBob123456** [comment]
Really, is there a place where I can see this new feature.
