### ISSUE TITLE
[Suggestion] Oraxen resource pack compatibility

### ISSUE THREAD

**Issue by The-Nyla** [Ticxo/Model-Engine-Wiki#7]
Hello, I was wondering if you could add an option to allow Modelengine to generate the resourcepack inside the Oraxen resourcepack folder, which would really help any servers using oraxen and modelengine, as it would eliminate the need to manually merge the modelengine pack into the Oraxen pack every time a new model is added or editied.

**Comment by Compasible2** [comment]
Good idea
