### ISSUE TITLE
[bug] Occasionally mobs will spawn without properly applying the model

### ISSUE THREAD

**Issue by The-Nyla** [Ticxo/Model-Engine-Wiki#8]
Modelengine version: R2.2.0
Server version: Purpur 1.17.1, build #1404
Mob type: zombie
dimension: end
mythicmobs version: 4.13

image:
![2021-11-15_14 14 41](https://user-images.githubusercontent.com/79489385/141840956-cae706ef-5032-4a76-8806-9fe367cda8fe.jpg)

**Comment by Jazzkuh** [comment]
I have this issue too.
